<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from /Users/jitendra/src/civicrm/tools/extensions/nz.co.fuzion.healthcheck/xml/schema/CRM/Healthcheck/HCDedupe.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:0e7d7dd75ebe060abc3f72b8c6e03db5)
 */

/**
 * Database access object for the HCDedupe entity.
 */
class CRM_Healthcheck_DAO_HCDedupe extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_healthcheck_dedupe';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique HCDedupe ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Contact
   *
   * @var int
   */
  public $rule_id;

  /**
   * @var datetime
   */
  public $action_log_date;

  /**
   * data associated with this group / name combo
   *
   * @var text
   */
  public $value;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_healthcheck_dedupe';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   */
  public static function getEntityTitle() {
    return ts('HCDedupes');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'id', 'civicrm_dedupe_rule_group', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Healthcheck_ExtensionUtil::ts('Unique HCDedupe ID'),
          'required' => TRUE,
          'where' => 'civicrm_healthcheck_dedupe.id',
          'table_name' => 'civicrm_healthcheck_dedupe',
          'entity' => 'HCDedupe',
          'bao' => 'CRM_Healthcheck_DAO_HCDedupe',
          'localizable' => 0,
          // 'FKClassName' => 'CRM_Dedupe_DAO_RuleGroup',
        ],
        'rule_id' => [
          'name' => 'rule_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Healthcheck_ExtensionUtil::ts('FK to Contact'),
          'where' => 'civicrm_healthcheck_dedupe.rule_id',
          'table_name' => 'civicrm_healthcheck_dedupe',
          'entity' => 'HCDedupe',
          'bao' => 'CRM_Healthcheck_DAO_HCDedupe',
          'localizable' => 0,
        ],
        'action_log_date' => [
          'name' => 'action_log_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => CRM_Healthcheck_ExtensionUtil::ts('Log Date'),
          'where' => 'civicrm_healthcheck_dedupe.action_log_date',
          'table_name' => 'civicrm_healthcheck_dedupe',
          'entity' => 'HCDedupe',
          'bao' => 'CRM_Healthcheck_DAO_HCDedupe',
          'localizable' => 0,
        ],
        'value' => [
          'name' => 'value',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => CRM_Healthcheck_ExtensionUtil::ts('Value'),
          'description' => CRM_Healthcheck_ExtensionUtil::ts('data associated with this group / name combo'),
          'where' => 'civicrm_healthcheck_dedupe.value',
          'table_name' => 'civicrm_healthcheck_dedupe',
          'entity' => 'HCDedupe',
          'bao' => 'CRM_Healthcheck_DAO_HCDedupe',
          'localizable' => 0,
          'serialize' => self::SERIALIZE_PHP,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'healthcheck_dedupe', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'healthcheck_dedupe', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
