-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_healthcheck_dedupe`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_healthcheck_dedupe
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_healthcheck_dedupe` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique HCDedupe ID',
     `rule_id` int unsigned    COMMENT 'FK to Contact',
     `action_log_date` datetime    ,
     `value` text    COMMENT 'data associated with this group / name combo'
,
        PRIMARY KEY (`id`)


,          CONSTRAINT FK_civicrm_healthcheck_dedupe_id FOREIGN KEY (`id`) REFERENCES `civicrm_dedupe_rule_group`(`id`) ON DELETE CASCADE
)    ;

